
GCCDIR :=  

NETCDF_DIR := /opt/local/lib
NETCDFINCDIR := /opt/local/include 
INCLUDEFLAGS += -I$(NETCDFINCDIR)
LIBS += -L $(NETCDF_DIR) -lnetcdf_c++4 -lconfig++

CUDADIR := ${HOME}/code/cuda/4.1/cuda
CUDALIBDIR = ${CUDADIR}/lib64
CUDA_ARCH := sm_13
CUDA_SDK_DIR := ${HOME}/cuda/NVIDIA_GPU_Computing_SDK
LIBCONFIGDIR := /opt/local
GOOGLE_PERF_DIR := ${HOME}/code/google-perftools
PAPI_DIR := ${HOME}/code/papi/gnu_${GNUVER}

CUDA_SDK_INC := $(CUDA_SDK_DIR)/C/common/inc


