PGI_OPENMPFLAGS := -acc -ta=nvidia -Minline=name:rk4_move,rk4_evalf,kj_interp1D -Minfo=accel,inline
PGI_DEBUGFLAGS := 
PGI_OPTFLAGS := 

CRAY_OPENMPFLAGS := -hpragma=acc,msgs
CRAY_DEBUGFLAGS := 
CRAY_OPTFLAGS := 

GNU_OPENMPFLAGS := 
GNU_DEBUGFLAGS := -g -O3
GNU_OPTFLAGS := 
