CC := cc 
CPP := CC
F90 =: ftn

ALGLIB_DIR := $(HOME)/alglib
INCLUDEFLAGS += -I $(ALGLIB_DIR)/cpp/src
LIBS += -L $(ALGLIB_DIR)/cpp/src -lalglib-pgi

INCLUDEFLAGS += -I $(HOME)/libconfig/libconfig_pgi/include
LIBS += -L $(HOME)/libconfig/libconfig_pgi/lib -lconfig++

NETCDF_DIR := 
INCLUDEFLAGS += 
LIBS += 


