#PGI_OPENMPFLAGS := -mp
PGI_OPENMPFLAGS := -acc -ta=nvidia -Minline=name:rk4_move,rk4_evalf,kj_interp -Minfo=accel,inline
PGI_DEBUGFLAGS := 
PGI_OPTFLAGS := -O3

#GCC_OPENMPFLAGS := -fopenmp
GCC_DEBUGFLAGS :=  -ggdb
#GCC_OPTFLAGS := -O0

