CC := cc 
CPP := CC
F90 =: ftn

ALGLIB_DIR := $(HOME)/alglib
INCLUDEFLAGS += -I $(ALGLIB_DIR)/cpp/src
LIBS += -L $(ALGLIB_DIR)/cpp/src -lalglib-cray

INCLUDEFLAGS += -I $(HOME)/libconfig/libconfig_cray/include
LIBS += -L $(HOME)/libconfig/libconfig_cray/lib -lconfig++

#NETCDF_DIR := 
INCLUDEFLAGS += -I $(NETCDF_DIR)/include
LIBS += -L $(NETCDF_DIR)/lib -lnetcdf_c++4  


