CC := nvcc
CPP := nvcc

USECUDA=1

NVCCFLAGS := --compiler-bindir `which CC`  -arch=sm_35 -O3

#ALGLIB_DIR := $(HOME)/alglib
#INCLUDEFLAGS += -I $(ALGLIB_DIR)/cpp/src
#LIBS += -L $(ALGLIB_DIR)/cpp/src -lalglib-cray

INCLUDEFLAGS += -I $(HOME)/kineticj_cuda/libconfig/libconfig_gnu/include -I/ccs/home/atj/cusplibrary
LIBS += -L $(HOME)/kineticj_cuda/libconfig/libconfig_gnu/lib -lconfig++

#NETCDF_DIR := 
INCLUDEFLAGS += -I $(NETCDF_DIR)/include
LIBS += -L $(NETCDF_DIR)/lib -lnetcdf_c++4  


